/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package libretadecontactossedeguanacaste.GUI;

import javax.swing.JOptionPane;
import libretadecontactossedeguanacaste.Logica.GestorDeDepartamentos;
import libretadecontactossedeguanacaste.Logica.GestorDeInstancias;
import libretadecontactossedeguanacaste.Modelos.Departamentos;
import libretadecontactossedeguanacaste.Modelos.Instancias;

/**
 *
 * @author KURISUTIAN
 */
public class AgregarDepartamento extends javax.swing.JFrame {
private GestorDeDepartamentos GestorDeDeartamentos;
    /**
    /**
     * Creates new form IngresarDepartamento
     */
    public AgregarDepartamento() {
        setSize(400, 400);
        
        initComponents();
        LlenarListaDeDepartamentos();
        ListarInstanciasParaComboBox();
    }
private void LlenarListaDeDepartamentos()
    {
        GestorDeDeartamentos=new GestorDeDepartamentos();
         JListaDeDepartamentos.setListData(GestorDeDeartamentos.ObtenerLosDepartamentos().toArray());
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Modificar = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JListaDeDepartamentos = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        AgregarNuevoDepartamento = new javax.swing.JButton();
        CbInstancias = new javax.swing.JComboBox();
        txtDepartamento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LbDepartamento = new javax.swing.JLabel();
        LbInstancia = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 400, 400));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        getContentPane().add(Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, 20));

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, -1, -1));

        JListaDeDepartamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PresionDeClick(evt);
            }
        });
        jScrollPane1.setViewportView(JListaDeDepartamentos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 172, 247));

        jLabel1.setText("Selecione un Departamento");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 172, -1));

        AgregarNuevoDepartamento.setText("Agregar");
        AgregarNuevoDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarNuevoDepartamentoActionPerformed(evt);
            }
        });
        getContentPane().add(AgregarNuevoDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));

        getContentPane().add(CbInstancias, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 172, -1));

        txtDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDepartamentoActionPerformed(evt);
            }
        });
        getContentPane().add(txtDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 194, -1));

        jLabel3.setText("Seleccione una instancia");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));

        jLabel4.setText("las opciones con \"--\" significan que no son departamentos, sino instancias");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));
        getContentPane().add(LbDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 83, -1, -1));
        getContentPane().add(LbInstancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 246, -1, -1));

        jLabel6.setText("Nombre del departamento");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarNuevoDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarNuevoDepartamentoActionPerformed

        if(SiElNombreExiste(txtDepartamento.getText()))
        {
            JOptionPane.showMessageDialog(null, "El nombre del departamento ya esta registrado");
              
        }else if(txtDepartamento.getText().equalsIgnoreCase(""))
        {
           JOptionPane.showMessageDialog(null, "no debe dejar el nombre vacio");
             
        }else
        {
             
            Departamentos elNuevoDepartamento=new Departamentos();

      
        elNuevoDepartamento.setDepartamento(txtDepartamento.getText());
        elNuevoDepartamento.setIdinstancia(ObtenerIdInstancia());
        
        GestorDeDeartamentos.IngresarDepartamentos(elNuevoDepartamento);

        }
        
        
        LlenarListaDeDepartamentos();
    }//GEN-LAST:event_AgregarNuevoDepartamentoActionPerformed

    private boolean SiElNombreExiste(String Nombre)
{
    boolean Existe=false;
    GestorDeDeartamentos=new GestorDeDepartamentos(); 
   
    for (Departamentos departamento : GestorDeDeartamentos.ObtenerLosDepartamentos()) {
        try {
            if(departamento.getDepartamento().equalsIgnoreCase(Nombre))
        {
            Existe=true;
        }
        } catch (NullPointerException e) {
            //JOptionPane.showMessageDialog(null, "el campo esta nulo");
        }
        
    }
   
   
   
   return Existe;
}
    public void ObtenerDatos(){
  Departamentos elDepartamento=new Departamentos();
  
        try {
          elDepartamento=(Departamentos)JListaDeDepartamentos.getSelectedValue();
          
        } catch (Exception e) {
        }
  
  txtDepartamento.setText(elDepartamento.getDepartamento());
  CbInstancias.setSelectedItem(ObtieneNombreDeInstancia(elDepartamento.getIdinstancia()));
          
    
    }
    
    public Instancias ObtieneNombreDeInstancia(int idInstancia)
    { 
        Instancias NombreDeLaInstancia=null;
     GestorDeInstancias gestorDeInstancias=new GestorDeInstancias();
        for (Instancias laInstancia : gestorDeInstancias.ObtenerLasInstancias()) {
            
            if(laInstancia.getIdinstancia()==idInstancia)
            {
                NombreDeLaInstancia=laInstancia;
            }
        }
       return NombreDeLaInstancia; 
    }
    
    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
       this.dispose();
    }//GEN-LAST:event_SalirActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed

        if(SiElNombreExiste(txtDepartamento.getText()) )
        {
            JOptionPane.showMessageDialog(null, "El nombre del departamento ya esta registrado");
              
        }else if(txtDepartamento.getText().equalsIgnoreCase(""))
        {
           JOptionPane.showMessageDialog(null, "no debe dejar el nombre vacio");
             
        }else if(JListaDeDepartamentos.isSelectionEmpty()) 
        {
            JOptionPane.showMessageDialog(null, "Debe selecionar un departamento para modificar");
            
        }else
        {
           
            
            Departamentos elNuevoDepartamento=(Departamentos)JListaDeDepartamentos.getSelectedValue();
             int acepto=JOptionPane.showConfirmDialog(null, "desea modificar el registro"+elNuevoDepartamento.getDepartamento());
       if(acepto==JOptionPane.YES_OPTION){
        elNuevoDepartamento.setDepartamento(txtDepartamento.getText());
        elNuevoDepartamento.setIdinstancia(ObtenerIdInstancia());
        
        GestorDeDeartamentos.ModificarDepartamento(elNuevoDepartamento);
       }else{JOptionPane.showMessageDialog(null, "No se modifico el registro");}
        }
        txtDepartamento.setText("");
        
        
        LlenarListaDeDepartamentos();        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarActionPerformed

    private void txtDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDepartamentoActionPerformed

    private void PresionDeClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PresionDeClick
       ObtenerDatos();
    }//GEN-LAST:event_PresionDeClick

    public Integer ObtenerIdInstancia(){
Integer idInstancia;
 Instancias laInstancia=(Instancias)CbInstancias.getSelectedItem();

idInstancia=laInstancia.getIdinstancia();
return idInstancia;
}
 
    
private void ListarInstanciasParaComboBox()
    {
        GestorDeInstancias GestorDeInstancias= new GestorDeInstancias();
         Instancias laInstancia= new Instancias();
     
        try {
            for (int i = 0; i < GestorDeInstancias.ObtenerLasInstancias().size(); i++) {
             
            laInstancia= GestorDeInstancias.ObtenerLasInstancias().get(i);
            CbInstancias.addItem(laInstancia);
              
        }
        } catch (Exception e) {
        }
         
         
        
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarDepartamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarNuevoDepartamento;
    private javax.swing.JComboBox CbInstancias;
    private javax.swing.JList JListaDeDepartamentos;
    private javax.swing.JLabel LbDepartamento;
    private javax.swing.JLabel LbInstancia;
    private javax.swing.JButton Modificar;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtDepartamento;
    // End of variables declaration//GEN-END:variables
}
