/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package libretadecontactossedeguanacaste.GUI;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import libretadecontactossedeguanacaste.Logica.GestorDeDepartamentos;
import libretadecontactossedeguanacaste.Logica.GestorDeInstancias;
import libretadecontactossedeguanacaste.Logica.GestorDeCarreras;
import libretadecontactossedeguanacaste.Logica.GestorDeContactos;
import libretadecontactossedeguanacaste.Logica.GestorDeTelefonos;
import libretadecontactossedeguanacaste.Logica.GestorDeCorreos;
import libretadecontactossedeguanacaste.Modelos.*;

/**
 *
 * @author KURISUTIAN
 */
public class IngresarContacto extends javax.swing.JFrame {
private DefaultTableModel DatosDeLaTabla;
private GestorDeInstancias GestorDeInstancias;
    /**
     * Creates new form IngresarContacto
     */
    public IngresarContacto() {
        initComponents();
        this.setLocationRelativeTo(null);
        ListarDepartamentosParaComboBox();
       ListarCarrerasParaComboBox();
        
    }

private void ListarDepartamentosParaComboBox()
    {
        GestorDeDepartamentos  GestorDeDepartamentos= new GestorDeDepartamentos();
       
         Departamentos elDepartamentos= new Departamentos();
     
        try {
            for (int i = 0; i < GestorDeDepartamentos.ObtenerLaListaDeDepartamentosOrdenada().size(); i++) {
             
            elDepartamentos= GestorDeDepartamentos.ObtenerLaListaDeDepartamentosOrdenada().get(i);
            CbDepartamentos.addItem(elDepartamentos);
              
        }
        } catch (Exception e) {
        }
         
         
        
    }



private void ListarCarrerasParaComboBox()
    {
        GestorDeCarreras GestorDeCarreras= new GestorDeCarreras();
         Carreras laCarrera= new Carreras();
     
        try {
           for (int i = 0; i < GestorDeCarreras.ObtenerLaListaDeCarrerasOrdenada().size(); i++) {
             
            laCarrera= GestorDeCarreras.ObtenerLaListaDeCarrerasOrdenada().get(i);
            CbCarreras.addItem(laCarrera);
              
        } 
        } catch (Exception e) {
        }
         
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        txtNombre = new javax.swing.JTextField();
        CbDepartamentos = new javax.swing.JComboBox();
        CbCarreras = new javax.swing.JComboBox();
        BtAgregar = new javax.swing.JButton();
        Telefonos = new javax.swing.JButton();
        Correos = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        CbTelefonos = new javax.swing.JComboBox();
        CbCorreos = new javax.swing.JComboBox();
        ChbDelSistema = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Contacto");
        setBounds(new java.awt.Rectangle(400, 200, 0, 0));
        setName("AgregarContacto"); // NOI18N
        setResizable(false);

        label2.setText("Nombre:");

        label3.setText("Departamento:");

        label4.setText("Carrera:");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        CbCarreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbCarrerasActionPerformed(evt);
            }
        });

        BtAgregar.setText("Agregar");
        BtAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAgregarActionPerformed(evt);
            }
        });

        Telefonos.setText("Telefonos");
        Telefonos.setEnabled(false);
        Telefonos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonosActionPerformed(evt);
            }
        });

        Correos.setText("Correos");
        Correos.setEnabled(false);
        Correos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorreosActionPerformed(evt);
            }
        });

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        CbTelefonos.setEnabled(false);

        CbCorreos.setEnabled(false);

        ChbDelSistema.setText("Del sistema");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ChbDelSistema)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CbCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(CbDepartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(70, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Salir)
                                    .addComponent(BtAgregar))
                                .addGap(25, 25, 25))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CbCorreos, 0, 197, Short.MAX_VALUE)
                                    .addComponent(CbTelefonos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Correos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Telefonos, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                                .addGap(155, 155, 155))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ChbDelSistema)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CbDepartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(CbCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addComponent(BtAgregar)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Telefonos)
                    .addComponent(CbTelefonos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CbCorreos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Correos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(Salir)
                .addContainerGap())
        );

        label2.getAccessibleContext().setAccessibleName("Nombre");
        label3.getAccessibleContext().setAccessibleName("Departamento");
        label4.getAccessibleContext().setAccessibleName("Carrera");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public int Sistema()
    {
        int estado=0;
        if(ChbDelSistema.isSelected())
        {
            estado=1;
        }
        
        return estado;
    }
    private void BtAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAgregarActionPerformed
       GestorDeContactos elContacto=new GestorDeContactos();
       Contactos elNuevoContacto=new Contactos();
        if(ElNombreEstaCorrecto(txtNombre.getText()))
        {
            
               elNuevoContacto.setIddepartamento(ObtenerIdDepartamento());  
      
               elNuevoContacto.setIdcarrera(ObtenerIdCarrera());  
           
            elNuevoContacto.setContacto(txtNombre.getText());
            elNuevoContacto.setEsDelSistema(Sistema());
            
         elContacto.IngresarDepartamentos(elNuevoContacto);
           JOptionPane.showMessageDialog(null, "Contacto registrado");
           LlenarTelefonos_Correos();
        }
    }//GEN-LAST:event_BtAgregarActionPerformed

    public boolean ElNombreEstaCorrecto(String txtDeIngreso)
    {
        boolean EsCorrecto=false;
        if(SiElNombreExiste(txtDeIngreso))
        {
            JOptionPane.showMessageDialog(null, "El nombre ya esta registrado");
              
        }else if(txtDeIngreso.equalsIgnoreCase(""))
        {
           JOptionPane.showMessageDialog(null, "no debe dejar el nombre vacio");
             
        }else{EsCorrecto=true;}
        
        
        return EsCorrecto;
    }
    
    
    
    
    private void LlenarTelefonos_Correos()
    {
        CbTelefonos.setEnabled(true);        
        CbCorreos.setEnabled(true);
        Telefonos.setEnabled(true);
        Correos.setEnabled(true);
        
        ObtenerTelefonos();
        ObtenerTelefonos();
    }
    
    public void LimpiarTelefonos()
    {
       int itemCount = CbTelefonos.getItemCount();

    for(int i=0;i<itemCount;i++){
        CbTelefonos.removeItemAt(0);
     } 
    }
    public void LimpiarCorreos()
    {
       int itemCount = CbCorreos.getItemCount();

    for(int i=0;i<itemCount;i++){
        CbCorreos.removeItemAt(0);
     } 
    }
        public void ObtenerTelefonos(){
          LimpiarTelefonos();
         GestorDeTelefonos  gestorDeTelefonos= new GestorDeTelefonos();
         Telefonos elTelefono= new Telefonos();
     
     
         for (int i = 0; i < gestorDeTelefonos.ObtenerLosTelefonos(IdCOntacto()).size(); i++) {
             
            elTelefono= gestorDeTelefonos.ObtenerLosTelefonos(IdCOntacto()).get(i);
            CbTelefonos.addItem(elTelefono);
              
        }
         
}
public void ObtenerCorreos(){
    LimpiarCorreos();    
    
GestorDeCorreos  gestorDeCorreos= new GestorDeCorreos();
         Correos elCorreo= new Correos();
     
     
         for (int i = 0; i < gestorDeCorreos.ObtenerLosCorreos(IdCOntacto()).size(); i++) 
         {
             
            elCorreo= gestorDeCorreos.ObtenerLosCorreos(IdCOntacto()).get(i);
            CbCorreos.addItem(elCorreo);
         }
         
}   
    
    
    
    private void CbCarrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbCarrerasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbCarrerasActionPerformed

    private void TelefonosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonosActionPerformed
       String telefono=JOptionPane.showInputDialog("Ingrese un numero telefonico");
       
       Telefonos elTelefonoAGuardar=new Telefonos();
       GestorDeTelefonos gestorDeTelefonos=new GestorDeTelefonos();
       
       elTelefonoAGuardar.setIdcontacto(IdCOntacto());
       elTelefonoAGuardar.setTelefono(telefono);
       gestorDeTelefonos.IngresarTelefono(elTelefonoAGuardar);
       ObtenerTelefonos();
    }//GEN-LAST:event_TelefonosActionPerformed

    private void CorreosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorreosActionPerformed
    String Correo=JOptionPane.showInputDialog("Ingrese un correo electronico");
       
       Correos elCorreoAGuardar=new Correos();
       GestorDeCorreos gestorDeCorreos=new GestorDeCorreos();
       
       elCorreoAGuardar.setIdcontacto(IdCOntacto());
       elCorreoAGuardar.setCorreo(Correo);
       gestorDeCorreos.IngresarCorreo(elCorreoAGuardar);
       ObtenerCorreos();        // TODO add your handling code here:
    }//GEN-LAST:event_CorreosActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
this.dispose();
    }//GEN-LAST:event_SalirActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    
    
    private boolean SiElNombreExiste(String Nombre)
{
    boolean Existe=false;
   GestorDeContactos elContacto=new GestorDeContactos(); 
   
    for (Contactos contacto : elContacto.ObtenerLasContactos()) {
        if(contacto.getContacto().equalsIgnoreCase(Nombre))
        {
            Existe=true;
        }
    }
   
   
   
   return Existe;
}
   
public int IdCOntacto()
{
    int idContacto=0;
 GestorDeContactos elContacto=new GestorDeContactos(); 
 for (Contactos contacto : elContacto.ObtenerLasContactos()) {
        if(contacto.getContacto().equalsIgnoreCase(txtNombre.getText()))
        {
            idContacto=contacto.getIdcontacto();
        }
    }
 return idContacto;
}

    
    public Integer ObtenerIdCarrera(){
Integer idCarrera;
Carreras laCarrera=(Carreras)CbCarreras.getSelectedItem();

idCarrera=laCarrera.getIdcarrera();    
return idCarrera;
}
public Integer ObtenerIdDepartamento(){
Integer idDepartamento;
Departamentos elDepartamento=(Departamentos)CbDepartamentos.getSelectedItem();

idDepartamento=elDepartamento.getIddepartamento();
return idDepartamento;
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresarContacto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAgregar;
    private javax.swing.JComboBox CbCarreras;
    private javax.swing.JComboBox CbCorreos;
    private javax.swing.JComboBox CbDepartamentos;
    private javax.swing.JComboBox CbTelefonos;
    private javax.swing.JCheckBox ChbDelSistema;
    private javax.swing.JButton Correos;
    private javax.swing.JButton Salir;
    private javax.swing.JButton Telefonos;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
