/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package libretadecontactossedeguanacaste.GUI;

import libretadecontactossedeguanacaste.Logica.GestorDeCarreras;
import libretadecontactossedeguanacaste.Logica.GestorDeDepartamentos;
import libretadecontactossedeguanacaste.Logica.GestorDeContactos;
import libretadecontactossedeguanacaste.Modelos.Carreras;
import libretadecontactossedeguanacaste.Modelos.Contactos;
import libretadecontactossedeguanacaste.Modelos.Departamentos;

/**
 *
 * @author KURISUTIAN
 */
public class ModificarContacto extends javax.swing.JFrame {
GestorDeContactos Gestor=new GestorDeContactos();
    Contactos ElContacto=new Contactos();
    
    /**
     * Creates new form ModificarContacto
     */
    public ModificarContacto() {
        initComponents();
        ListarDepartamentosParaComboBox();
        ListarCarrerasParaComboBox();
    }

    private void ListarDepartamentosParaComboBox()
    {
        GestorDeDepartamentos GestorDeDepartamento= new GestorDeDepartamentos();
         Departamentos elDepartamento= new Departamentos();
     
        try {
            for (int i = 0; i < GestorDeDepartamento.ObtenerLosDepartamentos().size(); i++) {
             
            elDepartamento= GestorDeDepartamento.ObtenerLosDepartamentos().get(i);
            CbDepartamento.addItem(elDepartamento);
              
        }
        } catch (Exception e) {
        }
              
    }
   private void ListarCarrerasParaComboBox()
    {
        GestorDeCarreras GestorDeCarreras= new GestorDeCarreras();
         Carreras laCarrera= new Carreras();
     
        try {
            for (int i = 0; i < GestorDeCarreras.ObtenerLasCarreras().size(); i++) {
             
            laCarrera= GestorDeCarreras.ObtenerLasCarreras().get(i);
            CbCarrera.addItem(laCarrera);
              
        }
        } catch (Exception e) {
        }
    }
   
   
   public Departamentos ObtieneNombreDelDepartamento(int idDepartamento)
    { 
        Departamentos NombreDelDepartamento=null;
        GestorDeDepartamentos gestorDeDepartamentos=new GestorDeDepartamentos();
        for (Departamentos elDepartamento : gestorDeDepartamentos.ObtenerLosDepartamentos()) {
            
            if(elDepartamento.getIddepartamento()==idDepartamento)
            {
                NombreDelDepartamento=elDepartamento;
            }
        }
       return NombreDelDepartamento; 
    }
    
    public Carreras ObtieneNombreDeLaCarrera(int idCarrera)
    { 
        Carreras NombreDeLaCarrera=null;
        GestorDeCarreras gestorDeCarreras=new GestorDeCarreras();
        for (Carreras laCarrera : gestorDeCarreras.ObtenerLasCarreras()) {
            
            if(laCarrera.getIdcarrera()==idCarrera)
            {
                NombreDeLaCarrera=laCarrera;
            }
        }
       return NombreDeLaCarrera; 
    }
    
   
    
   public void MandarElContactoParaModificar(Contactos elContactoAModificar)
   {
       ElContacto=elContactoAModificar;
       
       txtContacto.setText(ElContacto.getContacto());
       CbDepartamento.setSelectedItem(ObtieneNombreDelDepartamento(ElContacto.getIddepartamento()));
       CbCarrera.setSelectedItem(ObtieneNombreDeLaCarrera(ElContacto.getIdcarrera()));
          
   }
   
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtContacto = new javax.swing.JTextField();
        CbDepartamento = new javax.swing.JComboBox();
        CbCarrera = new javax.swing.JComboBox();
        Modificar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Modificar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtContacto)
                        .addComponent(CbDepartamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CbCarrera, 0, 327, Short.MAX_VALUE)))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(txtContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(CbDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(CbCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(Modificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        try {
            Contactos elContactoListoAModificar=ElContacto;
       elContactoListoAModificar.setContacto(txtContacto.getText());
       elContactoListoAModificar.setIdcarrera(ObtenerIdCarrera());
       elContactoListoAModificar.setIddepartamento(ObtenerIdDepartamento());
       
       Gestor.ModificarContacto(elContactoListoAModificar);
        } catch (Exception e) {
        }
        
       
    }//GEN-LAST:event_ModificarActionPerformed

       public Integer ObtenerIdCarrera(){
int idCarrera;
 Carreras laCarrera=(Carreras)CbCarrera.getSelectedItem();

idCarrera=laCarrera.getIdcarrera();
return idCarrera;
}
         public Integer ObtenerIdDepartamento(){
int idDepartamento;
 Departamentos elDepartamento=(Departamentos)CbDepartamento.getSelectedItem();

idDepartamento=elDepartamento.getIddepartamento();
return idDepartamento;
}
 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarContacto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CbCarrera;
    private javax.swing.JComboBox CbDepartamento;
    private javax.swing.JButton Modificar;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField txtContacto;
    // End of variables declaration//GEN-END:variables
}
