/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package libretadecontactossedeguanacaste.GUI;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import libretadecontactossedeguanacaste.Logica.GestorDeDepartamentos;
import libretadecontactossedeguanacaste.Modelos.Departamentos;
import libretadecontactossedeguanacaste.Logica.GestorDeContactos;
import libretadecontactossedeguanacaste.Logica.GestorDeCarreras;
import libretadecontactossedeguanacaste.Modelos.Carreras;
import libretadecontactossedeguanacaste.Modelos.Contactos;
import libretadecontactossedeguanacaste.Modelos.Instancias;
import libretadecontactossedeguanacaste.Logica.GestorDeInstancias;

/**
 *
 * @author KURISUTIAN
 */
public class Ventanainstancias extends javax.swing.JFrame {
    GestorDeDepartamentos GestorDeInstancias=new GestorDeDepartamentos();
    GestorDeContactos gestorDeContactos=new GestorDeContactos();
    /**
     * Creates new form Ventanainstancias
     */
    public Ventanainstancias() {
        initComponents();
       
       
        ListarInstanciasParaComboBox();
    }

    
    private void ListarInstanciasParaComboBox()
    {
       GestorDeInstancias gestorDeInstancias=new GestorDeInstancias();
         Instancias laInstancia= new Instancias();
     
        try {
            for (int i = 0; i < gestorDeInstancias.ObtenerLasInstancias().size(); i++) {
             
            laInstancia= gestorDeInstancias.ObtenerLasInstancias().get(i);
            CbInstancias.addItem(laInstancia);
              
        }
        } catch (Exception e) {
        }
         
         
        
    } 
    
private void ListarDepartamentosParaComboBox()
    {
        GestorDeDepartamentos GestorDeDepartamento= new GestorDeDepartamentos();
         Departamentos elDepartamento= new Departamentos();
     
        try {
            for (int i = 0; i < GestorDeDepartamento.ObtenerLosDepartamentos().size(); i++) {
             
            elDepartamento= GestorDeDepartamento.ObtenerLosDepartamentos().get(i);
            CbDepartamento.addItem(elDepartamento);
              
        }
        } catch (Exception e) {
        }
         
         
        
    }
private void ListarCarrerasParaComboBox()
    {
        GestorDeCarreras GestorDeCarreras= new GestorDeCarreras();
         Carreras laCarrera= new Carreras();
     
        try {
            for (int i = 0; i < GestorDeCarreras.ObtenerLasCarreras().size(); i++) {
             
            laCarrera= GestorDeCarreras.ObtenerLasCarreras().get(i);
            CbCarrera.addItem(laCarrera);
              
        }
        } catch (Exception e) {
        }
         
         
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JlistContactos = new javax.swing.JList();
        txtContacto = new javax.swing.JTextField();
        CbDepartamento = new javax.swing.JComboBox();
        CbCarrera = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        CbInstancias = new javax.swing.JComboBox();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JlistContactos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PrecionDeClick(evt);
            }
        });
        jScrollPane1.setViewportView(JlistContactos);

        CbDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbDepartamentoActionPerformed(evt);
            }
        });

        jButton2.setText("jButton1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("jButton1");

        jButton4.setText("jButton1");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        CbInstancias.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                seleccionDeLaInstancia(evt);
            }
        });

        jButton5.setText("Telefonos");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Correo");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addComponent(txtContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CbCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton2)
                                                .addGap(41, 41, 41)
                                                .addComponent(jButton4))
                                            .addComponent(CbDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(jButton5)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton6)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CbInstancias, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(CbInstancias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(jButton6))
                        .addGap(34, 34, 34)
                        .addComponent(txtContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CbDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(CbCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton4)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jButton3)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void CbDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbDepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbDepartamentoActionPerformed

    private void PrecionDeClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrecionDeClick
    ListarDepartamentosParaComboBox();
        ListarCarrerasParaComboBox();
        
        ObtenerDatos();
    }//GEN-LAST:event_PrecionDeClick

    private void seleccionDeLaInstancia(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_seleccionDeLaInstancia
        Instancias laInstancia=(Instancias)CbInstancias.getSelectedItem();
        ListarContactosParaLaLista(laInstancia.getIdinstancia());
    }//GEN-LAST:event_seleccionDeLaInstancia

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

     public void ObtenerDatos(){
        Contactos elContacto=new Contactos();
  
        try {
          elContacto=(Contactos)JlistContactos.getSelectedValue();
          
        } catch (Exception e) {
        }
  
  txtContacto.setText(elContacto.getContacto());
  CbDepartamento.setSelectedItem(ObtieneNombreDelDepartamento(elContacto.getIddepartamento()));
  CbCarrera.setSelectedItem(ObtieneNombreDeLaCarrera(elContacto.getIddepartamento()));
          
    
    }
    
    public Departamentos ObtieneNombreDelDepartamento(int idDepartamento)
    { 
        Departamentos NombreDelDepartamento=null;
        GestorDeDepartamentos gestorDeDepartamentos=new GestorDeDepartamentos();
        for (Departamentos elDepartamento : gestorDeDepartamentos.ObtenerLosDepartamentos()) {
            
            if(elDepartamento.getIddepartamento()==idDepartamento)
            {
                NombreDelDepartamento=elDepartamento;
            }
        }
       return NombreDelDepartamento; 
    }
    
    public Carreras ObtieneNombreDeLaCarrera(int idCarrera)
    { 
        Carreras NombreDeLaCarrera=null;
        GestorDeCarreras gestorDeCarreras=new GestorDeCarreras();
        for (Carreras laCarrera : gestorDeCarreras.ObtenerLasCarreras()) {
            
            if(laCarrera.getIdcarrera()==idCarrera)
            {
                NombreDeLaCarrera=laCarrera;
            }
        }
       return NombreDeLaCarrera; 
    }
    
    public List<Departamentos>ObtenerContactosDeInstancias()
    {
        List<Departamentos> laListaDeInstancias= new ArrayList<>();
        
        for (Departamentos elDepartamento : GestorDeInstancias.ObtenerLosDepartamentos()) {
            
            if (elDepartamento.getDepartamento().contains("-")) {
                laListaDeInstancias.add(elDepartamento);
            }
            
        }
                return laListaDeInstancias;
    }
    
    public void ListarContactosParaLaLista(int idInstancia)
    {
        List<Contactos> laListaDeContactos=gestorDeContactos.ObtenerLasContactos();
        List<Contactos> laListaDeContactosParaLaLista=new ArrayList<>();
        
        List<Departamentos> laListaDeInstanciasSinDepartamentos= ObtenerContactosDeInstancias();
        
        for (Departamentos laInstancia : laListaDeInstanciasSinDepartamentos) {
            if (laInstancia.getIdinstancia()==idInstancia) {
               
            for (Contactos elContacto : laListaDeContactos) {
                if (laInstancia.getIddepartamento()==elContacto.getIddepartamento()) {
                   laListaDeContactosParaLaLista.add(elContacto);
                }
            }
        }
        }
         JlistContactos.setListData(laListaDeContactosParaLaLista.toArray());
       
    }
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventanainstancias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventanainstancias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventanainstancias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventanainstancias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventanainstancias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CbCarrera;
    private javax.swing.JComboBox CbDepartamento;
    private javax.swing.JComboBox CbInstancias;
    private javax.swing.JList JlistContactos;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtContacto;
    // End of variables declaration//GEN-END:variables
}
