/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package libretadecontactossedeguanacaste.GUI;
import libretadecontactossedeguanacaste.Logica.CrearBD;
import libretadecontactossedeguanacaste.Logica.GestorDeInstancias;
import libretadecontactossedeguanacaste.Logica.GestorDeDepartamentos;

/**
 *
 * @author KURISUTIAN
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        JmenuCrearBD = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        MenuInstancias = new javax.swing.JMenuItem();
        MenuDepartamento = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        Carreras = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        Salir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        JmenuInstancias = new javax.swing.JMenuItem();
        Departamentos = new javax.swing.JMenuItem();
        Coordinaciones = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        MenuAgregarContacto = new javax.swing.JMenu();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(400, 200, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        JmenuCrearBD.setText("Archivos");

        jMenuItem1.setText("Crear Base De Datos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        JmenuCrearBD.add(jMenuItem1);

        jMenuItem2.setText("Actualizar Base de Datos");
        JmenuCrearBD.add(jMenuItem2);

        jMenu1.setText("Agregar");

        MenuInstancias.setText("Instancia");
        MenuInstancias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuInstanciasActionPerformed(evt);
            }
        });
        jMenu1.add(MenuInstancias);

        MenuDepartamento.setText("Departamento");
        MenuDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuDepartamentoActionPerformed(evt);
            }
        });
        jMenu1.add(MenuDepartamento);

        jMenuItem7.setText("Coordinación");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        Carreras.setText("Carrera");
        Carreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarrerasActionPerformed(evt);
            }
        });
        jMenu1.add(Carreras);

        JmenuCrearBD.add(jMenu1);

        jMenuItem5.setText("Guardar Copia ");
        JmenuCrearBD.add(jMenuItem5);

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        JmenuCrearBD.add(Salir);

        jMenuBar1.add(JmenuCrearBD);

        jMenu2.setText("Ver Contactos");

        JmenuInstancias.setText("Instancias");
        JmenuInstancias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmenuInstanciasActionPerformed(evt);
            }
        });
        jMenu2.add(JmenuInstancias);

        Departamentos.setText("Departamentos");
        Departamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepartamentosActionPerformed(evt);
            }
        });
        jMenu2.add(Departamentos);

        Coordinaciones.setText("Coordinaciones");
        Coordinaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoordinacionesActionPerformed(evt);
            }
        });
        jMenu2.add(Coordinaciones);

        jMenuItem3.setText("Profesores");
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        MenuAgregarContacto.setText("Agregar Contacto");
        MenuAgregarContacto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuAgregarContactoMouseClicked(evt);
            }
        });
        jMenuBar1.add(MenuAgregarContacto);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        CrearBD baseDeDatos= new CrearBD();
        try {
          baseDeDatos.CrearLaBaseDeDatos();   
        } catch (Exception e) {
        }
       // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void JmenuInstanciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmenuInstanciasActionPerformed
        Ventanainstancias  ventanaDeInstancias= new Ventanainstancias();
        ventanaDeInstancias.setVisible(true);
    }//GEN-LAST:event_JmenuInstanciasActionPerformed

    private void DepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepartamentosActionPerformed
//VentanaDepartamentos nuevaVentana= new VentanaDepartamentos();
//nuevaVentana.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_DepartamentosActionPerformed

    private void CoordinacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoordinacionesActionPerformed
VentanaCoordinaciones ventanaNueva=new VentanaCoordinaciones();
ventanaNueva.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_CoordinacionesActionPerformed

    private void MenuAgregarContactoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuAgregarContactoMouseClicked
        IngresarContacto elNuevoContacto= new IngresarContacto();
        elNuevoContacto.setVisible(true);
    }//GEN-LAST:event_MenuAgregarContactoMouseClicked

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
       System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void MenuInstanciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuInstanciasActionPerformed
        AgregarInstancias ventana=new AgregarInstancias();
        ventana.setVisible(true);
    }//GEN-LAST:event_MenuInstanciasActionPerformed

    private void MenuDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDepartamentoActionPerformed
        AgregarDepartamento ventana=new AgregarDepartamento();
        ventana.setVisible(true);
    }//GEN-LAST:event_MenuDepartamentoActionPerformed

    private void CarrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarrerasActionPerformed
         AgregarCarrera ventana=new AgregarCarrera();
        ventana.setVisible(true);
    }//GEN-LAST:event_CarrerasActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        AgregarCoordinacion ventana=new AgregarCoordinacion();
        ventana.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Carreras;
    private javax.swing.JMenuItem Coordinaciones;
    private javax.swing.JMenuItem Departamentos;
    private javax.swing.JMenu JmenuCrearBD;
    private javax.swing.JMenuItem JmenuInstancias;
    private javax.swing.JMenu MenuAgregarContacto;
    private javax.swing.JMenuItem MenuDepartamento;
    private javax.swing.JMenuItem MenuInstancias;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    // End of variables declaration//GEN-END:variables
}
